name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    - name: Run all tests with stable defaults
      run: cargo test

    - name: Run tests without default features
      run: cargo test --no-default-features

    - name: Run with all unstable features
      run: cargo test --features="nightly_default"

    - name: Run tests in release
      run: cargo test --features="nightly_default" --release 

    - name: Build documentation
      run: cargo doc --features="nightly_default" --no-deps


  build_stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Run tests without default features
      run: cargo test --no-default-features

    - name: Run with all stable features
      run: cargo test

    - name: Run tests in release
      run: cargo test --release 

    - name: Build documentation
      run: cargo doc --no-deps