name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_nightly:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: nightly
        override: true

    - name: Run all tests
      run: cargo test

    - name: Run tests without default features
      run: cargo test --no-default-features

    - name: Run with all stable features
      run: cargo test --no-default-features --features="unsafe_algos seed_with"

    - name: Run tests in release
      run: cargo test --release 

    - name: Build documentation
      run: cargo doc --no-deps


  build_stable:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Run tests without default features
      run: cargo test --no-default-features

    - name: Run with all stable features
      run: cargo test --no-default-features --features="unsafe_algos seed_with"

    - name: Run tests in release
      run: cargo test --no-default-features --features="unsafe_algos seed_with" --release 

    - name: Build documentation
      run: cargo doc --no-default-features --no-deps