name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run all tests
      run: cargo +nightly test

    - name: Run tests with default features
      run: cargo +nightly test --no-default-features

    - name: Run tests in release
      run: cargo +nightly test --release 

    - name: Build documentation
      run: cargo +nightly test --no-deps